---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

sudo: false
dist: trusty

cache: yarn

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    - tribute-basic-test-cases

jobs:
  fail_fast: true
  allow_failures:

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - yarn run test-single-run

before_install:
  - yarn --version

script:
  - yarn run build
